import spring.env
server.port=${PORT:8080}

# Nome da aplicação
spring.application.name=servidorlocal

# Configuração da base de dados H2 guardada em ficheiro local
spring.datasource.url=${DATABASE_URL:${DB_URL:jdbc:h2:file:./dados/minhabase}}

spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}


# Cria/Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

server.jpa.hibernate.ddl-size=128KB
server.tomcat.max-http-form-post-size=2MB
# Permite aceder à H2 Console via navegador (opcional)
spring.h2.console.enabled=true

# Configuração do Servidorde de Email(Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

# Configuração avançada de segurança exigidas pelo Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET:qwertyuioplkjhgfdsazxcvbnm741258963q3tfgtaaviranDSAIOOSDFAKBASDFIBWSDD}